### ISSUE TITLE
`1000n << 10000000n` takes forever

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#1053]
As mentioned in #883, running the following code stalls the interpreter:
```javascript
1000n << 10000000n;
```

This is controlled [here](https://github.com/boa-dev/boa/blob/7b103a5c0bf29150a9bace87b17b39c9e0e7750d/boa/src/value/operations.rs#L319-L324) and [here](https://github.com/boa-dev/boa/blob/7b103a5c0bf29150a9bace87b17b39c9e0e7750d/boa/src/value/operations.rs#L331-L336). We don't ever check if the generated `BigInt` would be out of range.

The [spec](https://tc39.es/ecma262/#sec-numeric-types-bigint-leftShift) here is not very clear, but I guess we should be checking if any of the operands would make it go out of range before trying to execute the operation.

**Comment by jevancc** [comment]
As far as I know, v8 takes forever to run and SpiderMonkey throws an early range error (too large to allocate). The current implementation should be fine since the spec defines the size of `BigInt` is not limited, and so does the crate `num-bigint` we use.

But it is doable to set a reasonable size limit for `BigInt`. For reference, this is how SpiderMonkey estimates the shift result's length and check the limit:
https://searchfox.org/mozilla-central/source/js/src/vm/BigIntType.cpp#2180
https://searchfox.org/mozilla-central/source/js/src/vm/BigIntType.cpp#146

**Comment by jedel1043** [comment]
Not a bug, this is just the correct behaviour for someone trying to shift a bigint by a massive amount.
