### ISSUE TITLE
Can't compile example classes.rs

### ISSUE THREAD

**Issue by gufoe** [boa-dev/boa#1262]
Hello, thanks for the cool project.

I cannot compile the classes example:
https://github.com/boa-dev/boa/blob/master/boa/examples/classes.rs

I imported boa like this: `Boa = "0.11.0"`
I get the same error on both stable and nightly.

```
$ cargo run

    Blocking waiting for file lock on build directory
   Compiling jsint v0.1.0 (/tmp/jsint)
error[E0433]: failed to resolve: could not find `gc` in the list of imported crates
  --> src/main.rs:15:17
   |
15 | #[derive(Debug, Trace, Finalize)]
   |                 ^^^^^ could not find `gc` in the list of imported crates
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `gc` in the list of imported crates
  --> src/main.rs:15:24
   |
15 | #[derive(Debug, Trace, Finalize)]
   |                        ^^^^^^^^ could not find `gc` in the list of imported crates
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `gc` in the list of imported crates
  --> src/main.rs:15:17
   |
15 | #[derive(Debug, Trace, Finalize)]
   |                 ^^^^^ not found in `gc`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
   |
1  | use boa::gc::Trace;
   |
1  | use crate::Trace;
   |

error[E0433]: failed to resolve: could not find `gc` in the list of imported crates
  --> src/main.rs:15:17
   |
15 | #[derive(Debug, Trace, Finalize)]
   |                 ^^^^^ not found in `gc`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
   |
1  | use boa::gc::Finalize;
   |
1  | use crate::Finalize;
   |

error: aborting due to 4 previous errors

```

I get the same error every time I try to derive Trace or Finalize.
I tested with both the stable and nightly toolchain.

- OS: debian 
- Version: testing
- Target triple: Debian 5.10.24-1 (2021-03-19) x86_64 GNU/Linux
- Rustc version: rustc 1.54.0-nightly (5c0292654 2021-05-11)
- Stable rust: rustc 1.52.1 (9bc8c42bb 2021-05-09)

**Comment by carterisonline** [comment]
I also ran into this issue while trying to embed Boa into my app. A few key issues stand out to me here:

(note: I am running this code in my own testing project; my `main.rs` is identical to Boa's `boa/examples/classes.rs`)

1. Your issue can be resolved by importing `gc` into your `Cargo.toml` (I used version 0.4)
2. Upon applying that change, the example shows a __new__ error regarding the derive macro for `boa::gc::Trace`:
```sh
$ cargo check
...
error[E0277]: the trait bound `Person: boa::gc::Trace` is not satisfied
  --> src/main.rs:49:6
   |
49 | impl Class for Person {
   |      ^^^^^ the trait `boa::gc::Trace` is not implemented for `Person`
   | 
  ::: /home/carter/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.11.0/src/class.rs:71:18
   |
71 | pub trait Class: NativeObject + Sized {
   |                  ------------ required by this bound in `boa::class::Class`

error: aborting due to previous error
```
3. Assuming that the `console` feature is enabled, this example will compile fine using the upstream git link rather than version 0.11:
```toml
Boa = {git = "https://github.com/boa-dev/boa", features = ["console"]}
```
4. However, this will result in an Error unwrap after `eval()`, that stems from the method `person.sayHello()`. Removing the use of this method from the JS source code will completely evaluate the code without errors.

[(Output of the previous step)](https://pastebin.com/1QvUCL7x)

- System: Linux 5.12.12-arch1-1, Arch Linux + KDE Plasma 5.22.1
- Target triple: x86_64-unknown-linux-gnu
- rustc 1.55.0-nightly (6a758ea7e 2021-06-22)
