### ISSUE TITLE
Add safety information about the `Readable` trait.

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#1761]
Currently, in the VM `Readable` trait we have a `# Safety` section but no safety information. Let's add it.

**Comment by HalidOdat** [comment]
It's unsafe because it should only be implemented on type that don't implement `Drop`, since primitives like `u32`, `f64` don't  implement `Drop` we can "safely" implement unsafe `Readable`. Currently rust stable does not support [negative trait bounds](https://doc.rust-lang.org/beta/unstable-book/language-features/negative-impls.html) we could call drop on a type twice, or more or not at all. We _could_ potentially go around this with [`ManuallyDrop`](https://doc.rust-lang.org/std/mem/struct.ManuallyDrop.html), but then we have to handle destruction somewhere else. In any case we currently don't need to have objects that implement `Drop` as opcode operand.
