### ISSUE TITLE
Enable a parsed StatementList to be passed across async/await boundaries

### ISSUE THREAD

**Issue by tobiemh** [boa-dev/boa#1864]
Hi,

I'm trying to implement Boa within a Rust web server (running behind [Warp](https://github.com/seanmonstar/warp)), which has the requirement that all async code must also be Send as it *may* get processed on an alternative Tokio thread. Currently the one thing preventing a parsed [StatementList](https://boa-dev.github.io/boa/doc/boa_engine/syntax/ast/node/statement_list/struct.StatementList.html) from being sent across threads is the Rc<RawBigInt> in [src/bigint.rs](https://github.com/boa-dev/boa/blob/8c92a8fa25c1339b639a5acc5c3133ae8df670a2/boa_engine/src/bigint.rs#L24).

https://github.com/boa-dev/boa/blob/8c92a8fa25c1339b639a5acc5c3133ae8df670a2/boa_engine/src/bigint.rs#L23-L25

Removing the Rc around the RawBigInt allows the async code to build, and I don't think that it negatively affects performance when [operating on RawBigInt values](https://github.com/boa-dev/boa/blob/8c92a8fa25c1339b639a5acc5c3133ae8df670a2/boa_engine/src/bigint.rs#L216-L254) together.

Just to make it clear, this requirement **DOES NOT** have anything to do with evaluating a Boa Context in an asynchronous way, and **DOES NOT** have anything to do with async/await within the Boa Javascript runtime. Instead this would allow a parsed StatementList from being passed across async/await boundaries or across threads.

I have implemented this small change here: https://github.com/tobiemh/boa/commit/7cdc0487645f063176b261bf40904f97931b2460, but I wanted to hear thoughts on this proposal before submitting any pull request (if desired).

**Comment by Razican** [comment]
The usage of `Rc` here is to reduce the memory footprint, but I'm curious, does the rest work? We use a single-threaded garbage collector very extensively, which I would expect not to work in this scenario, or at least not to work properly. Note that JavaScript is single-threaded, so the whole context initialization, parsing, compilation and execution should happen in the same thread. We should check if the garbage collector works when sending stuff across thread boundaries or we end up with leaked memory.

I would like the input of @HalidOdat here, since I think he worked on part of this.

**Comment by tobiemh** [comment]
@Razican in my use case I'm parsing Javascript into an AST (`StatementList`) and storing it serialized. When a request is made to the webserver, the StatementList is deserialized and executed. However, the `StatementList` is the value that gets passed around across Rust async/await boundaries (with the only issue being the `Rc` in `BigInt`).

When the AST is compiled and executed, this happens within an `async fn` and does not cross any Rust async/await boundary... 

```rust
pub async fn run_code(ast: StatementList) -> Result<(), Error> {
    let src = Context::compile(ast);
    let mut run = Context::new();
    match run.execute(src) {
        Ok(_) => todo!(),
        Err(_) => todo!(),
    }
}
```

With the proposed change, the AST (`StatementList`) can be passed around freely across async/await boundaries. In addition it would allow for a `StatementList` to be passed to a separate thread to compile and execute.

**Comment by HalidOdat** [comment]
> I would like the input of @HalidOdat here, since I think he worked on part of this.

The main reason for making it  have `Rc<_>` for two reasons:
1. So AST cloning was cheap (which we don't do that anymore)
2. To make the AST smaller (but this can be achieved with `Box<_>` as well)

So we can make the AST `Send` if we use `Box` since it implements `Send`.

**Comment by tobiemh** [comment]
Perfect, this sounds great! Thanks for both your input @Razican and @HalidOdat. Looking forward to a PR!

**Comment by Razican** [comment]
It looks like solving this is not an easy task. Anything that avoids Rc pointers will make the whole engine much, much slower. An option would be to change them for `Arc` by selecting a feature. For now I'm removing this feature from the upcoming 0.14 release, since we cannot handle such high overhead (up to 15% worse benchmarks).

**Comment by Razican** [comment]
After a thorough review, we noticed that the changes in performance were +/- 1.5%, with some improvements in some cases even. So this made it for 0.14!
