### ISSUE TITLE
Set-up benchmarking against other engines

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#1924]
Currently, we run benchmarks to improve (or at least not regress) on the performance of Boa. This is a very good approach, but we are missing proper benchmarking against other JavaScript engines.

Particularly, it would be interestint to benchmark against
 - Spidermonkey
 - V8 (both in Node and in Deno)

Any other possible engine would also fit. The idea is to store these comparisons for each commit, the same way we do it for our own benchmarks. We can either create new benchmarks, or try to replicate our benchmarks in those engines, and store their values on each commit.

**Comment by jasonwilliams** [comment]
Just dumping some ideas..

Hyperfine seems like it would be good for this, and maybe a separate repo under the boa-dev umbrella which can periodically run.

Something like test262 would be too much, so would need to be just a couple of JS scripts, like 3 or 4 max for now.

**Comment by birdbrainswagtrain** [comment]
[This repo](https://github.com/mozilla/arewefastyet/tree/master/benchmarks) is pretty old but it contains a bunch of benchmark scripts that should be usable.

**Comment by wusyong** [comment]
> [This repo](https://github.com/mozilla/arewefastyet/tree/master/benchmarks) is pretty old but it contains a bunch of benchmark scripts that should be usable.

quickJS [benchmark](https://bellard.org/quickjs/bench.html) with [v8-v7](https://github.com/mozilla/arewefastyet/tree/master/benchmarks/v8-v7). Maybe we can see some results between boa, quickJS, and v8.

**Comment by wusyong** [comment]
I just modify the benchmark above so it can work with boa. Here's the result from @CYBAI 
```
Richards: 8.64
DeltaBlue: 7.19
RayTrace: 30.0
----
Score (version 7): 12.3
```

And here's V8's:

```
Richards: 26212
DeltaBlue: 60518
RayTrace: 65267
----
Score (version 7): 46956
```

I haven't tested the rest because some of them will stuck.

**Comment by jasonwilliams** [comment]
Hey @wusyong great work on this, I had some questions.
Are there any current benchmarks the engines are being judged by today that Boa can be added to or is this the best option? 
What does those numbers mean and are those names [Richards] just some test cases?
What does the score mean?

**Comment by wusyong** [comment]
I don't this is the best benchmark tbh. This benchmark has been archived by mozilla.
I think QuickJS choose this just for quick result. It doesn't provide metrics to keep monitor ever since.
But V8 results from @CYBAI is similar to QuickJS posted.
We can get some idea about the gaps between those engines.

**Comment by gkorland** [comment]
@jasonwilliams @wusyong I think that if boa is around these numbers 
```
![image](https://user-images.githubusercontent.com/753206/207280983-59b8d85e-fa59-4fb0-96d3-523399b811d4.png)

**Comment by jasonwilliams** [comment]
Thanks for this @lastmjs its quite informative. So I think we need to do a few things here:
- It would be good to have some benchmarking framework that builds on this, something we could run on CI maybe.
- We’re aware we’re slower than other engines, we lack inline caching, hidden classes, and a Just In Time compiler, plus various other things. We should start tracking the progress of these more closely. Maybe even set up a project to group these by. 

Let me know if there’s any of these you’d like to collaborate on it any.

I understand how important performance is and we’ll hopefully chat about it when we’re next together.

**Comment by lastmjs** [comment]
I can setup the benchmarking CI using the benchmarking framework I shared if that's what we'd like to do. It should be relatively simple and would at least get us started with measuring.

Also, for my company's purposes we really need optimizations besides JIT because we're executing in a Wasm runtime. There should be ~30x improvement without JIT.

**Comment by jasonwilliams** [comment]
@lastmjs it would be good to see https://github.com/GoogleChromeLabs/jsvu be used so we can test against engines other than quickjs

here is an example https://github.com/mathiasbynens/string-prototype-replace-regexp-benchmark/blob/main/bench.sh

would be good to see something like hyperfine used too

**Comment by lastmjs** [comment]
I'm suggesting using the V8 benchmarks, are you suggesting combining those benchmarks with `jsvu` so that we run the benchmarks against various engines in CI? Or are you suggesting another benchmarking framework be used?

The simplest thing to start with would be getting the V8 benchmarks to run in CI, so we can compare against this chart: https://bellard.org/quickjs/bench.html

**Comment by jasonwilliams** [comment]
> are you suggesting combining those benchmarks with jsvu so that we run the benchmarks against various engines in CI?

Yes I'm suggesting this.
Do you have a link to the V8 benchmarks?

**Comment by lastmjs** [comment]
This is all done with the V8 benchmarks: https://bellard.org/quickjs/bench.html

**Comment by jasonwilliams** [comment]
In order for us to keep on track with making sure we're focusing on performance i propose we retire the [current benchmarks](https://boajs.dev/boa/dev/bench/) we have and migrate to the V8 benchmarks quickjs were using. Funnily enough quickJS have moved away from that benchmark suite now to something they have built-in but I still think it should make for a better benchmark that we have today.

The current suite is no longer useful or serving its purpose, it was created a long time ago and there have been so many optimizations since then that the numbers on the graphs are so out of magnitude you can't make use of it today. Also the things we were benchmarking or checking have either changed or we've refactored so we (the maintainers) don't look at that page too often.

I would propose us having a nightly job which can take the bench-v8 from the archive like [@lastmjs showed](https://github.com/boa-dev/boa/issues/1924#issuecomment-1437314041) and run the latest boa vs other engines from [esvu](https://github.com/devsnek/esvu) then print the results into a JSON file on the [data repo](https://github.com/boa-dev/data). The website can take that data and generate some graphs with it

**Comment by jasonwilliams** [comment]
We have new benchmarks https://boajs.dev/benchmarks

**Comment by jedel1043** [comment]
Closing by the previous comment.
