### ISSUE TITLE
to_json u32 error

### ISSUE THREAD

**Issue by lastmjs** [boa-dev/boa#1961]
**Describe the bug**

I have been using the new JsValue `to_json` functionality and I'm running into some issues. I have a valid `u32` represented in JavaScript that should be convertible to a u32 in Rust, but it isn't.

**To Reproduce**

```rust
fn main() {
    println!("get_u32: {}", get_u32());
}

fn get_u32() -> u32 {
    let mut context = boa_engine::Context::default();

    let return_value = context.eval(r#"
        4294967295
    "#).unwrap();

    serde_json::from_value(return_value.to_json(& mut context).unwrap()).unwrap()
}
```

**Expected behavior**

This should print `get_u32: 4294967295` and should not error out. Instead I get this error:

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: floating point `4294967295`, expected u32", line: 0, column: 0)', src/main.rs:12:74
```

**Build environment (please complete the following information):**

- OS: Ubuntu 20.04
- Version: latest main
- Target triple: wasm32-unknown-unknown or x86_64-unknown-linux-gnu
- Rustc version: rustc 1.58.1 (db9d1b20b 2022-01-20)

**Additional context**

I am also running into issues where JS numbers that should be representable in Rust as integers are instead `Rational`s, thus causing `to_json` to fail. I will open another issue for those problems, but I think they might be related to this issue.

**Comment by lastmjs** [comment]
I certainly hope you'll support it, the `to_json` combined with `serde_json::from` is such a simple DX.

**Comment by lastmjs** [comment]
Also it would be nice to have support for most of the default Rust primitive values as far as possible, perhaps with some easy interop with `bigint`.

**Comment by jedel1043** [comment]
Also, consider that we don't NEED to support u32 to add this feature, we would just try to convert the `f64`s to `u32`s when converting to json, but it would be good to determine our priorities about integer support.

**Comment by HalidOdat** [comment]
Hmmm... Adding `u32` integers, in addition to `i32` would be a performance penalty (besides complexity) for any number operation.

As suggested by @jedel1043 It would be far better to convert the `f64` value to `u32` in `to_json()`.

**Comment by lastmjs** [comment]
I'm trying to build a workaround for this in my project, and it's proving a tad more difficult than I thought. I just want to get a reading on what I can expect from boa.

It would be ideal for boa to allow conversion to any of the following. Since `BigInt` is part of the language, I believe each conversion should be possible:

* `i128` (representable in JS with a `bigint` primitive)
* `i64` (representable in JS with a `bigint` primitive)
* `i32` (representable in JS with a `number` primitive)
* `i16` (representable in JS with a `number` primitive)
* `i8` (representable in JS with a `number` primitive)

* `u128` (representable in JS with a `bigint` primitive)
* `u64` (representable in JS with a `bigint` primitive)
* `u32` (representable in JS with a `number` primitive)
* `u16` (representable in JS with a `number` primitive)
* `u8` (representable in JS with a `number` primitive)

* `float64` (representable in JS with a `number` primitive)
* `float32` (representable in JS with a `number` primitive)

If I'm wrong about any of the above please let me know.

**Comment by Razican** [comment]
I don't think this is an issue with Boa, honestly. We offer all the conversions from Rust types to JsValue you mention, except for `i128`, which I would be happy to add, it's pretty straightforward.

But, your code is trying to do a different thing. You are trying to convert a JavaScript value (`4294967295`) into a serde JSON type, which, since it's a numeric type, it will be encoded as a [`serde_json::Number`](https://docs.serde.rs/serde_json/struct.Number.html) as a `f64`, since numeric types in JavaScript are 64-bit floating point numbers: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#number_type

Here is an example in the Rust playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fb1691b93846342c1478cbe5b66cb913

It's true that `serde_json` has a special treatment for `u64` and `i64` (and smaller types), where if you pass an integer to it, you can bring it back as an integer, and indeed, if you use something that can be stored in a `i32` it will work "by chance", but actually, converting "any numeric JavaScript value" to a `u32` is undefined behaviour. It only works for `i32` because we have an optimisation in place, which we might want to remove for JSON conversions looking at how it can cause some misconceptions.

As I mention, JavaScript numeric values are always an `f64`, and they should be treated as such. This, for example, works: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=16db0a2a7b992a75a0e543169a6b6ec2

I recommend converting it to an `f64` and then casting it to whatever you would need.

I don't think there is much else to do from us here apart from implementing the `i128` to `JsValue` conversion. I have created #1970 to track this, in case someone wants to tackle it.

**Comment by lastmjs** [comment]
Thanks for the clarification, that makes sense. Is there any functionality to convert a JsValue into other types? I suppose that's what I'm really using serde_json for. I am using `serde_json::from_value` to just get the `JsValue` into the other type.

I think it could be very valuable to have a direct transformation from JsValue into any type the user chooses. Thoughts on this?

**Comment by Razican** [comment]
> Thanks for the clarification, that makes sense. Is there any functionality to convert a JsValue into other types? I suppose that's what I'm really using serde_json for. I am using `serde_json::from_value` to just get the `JsValue` into the other type.
> 
> 
> 
> I think it could be very valuable (less complicated, more precise, more efficient) to have a direct transformation from JsValue into any type the user chooses. I believe that would solve the number problems I am having more easily than trying to get `serde_json` to implement this. Thoughts on this?

This would actually make a lot of sense, yes. We could have a `TryFromJsValue` trait that would receive a context and a `JsValue` and try to perform the conversion. Just thinking out loud, but I could imagine a similar API to the `Serializa`/`Deserialize` APIs in serde.

**Comment by lastmjs** [comment]
Oh yes! This is sounding excellent!

**Comment by lastmjs** [comment]
The new `IntoJsValue` and `TryFromJsValue` traits have solved this problem for me on my branch. Discussion should probably move here: https://github.com/boa-dev/boa/issues/1975
