### ISSUE TITLE
undefined to JSON is not implemented

### ISSUE THREAD

**Issue by lastmjs** [boa-dev/boa#1974]
I've been relying on the functionality from https://github.com/boa-dev/boa/commit/8c92a8fa25c1339b639a5acc5c3133ae8df670a2 and I keep running into the fact that `to_json` does not have an implementation for `undefined`. Why was it left unimplemented? Is it difficult to implement?

Also the fact that `BigInt` is also not implemented in `to_json` makes the idea of a TryFromJsValue trait even more appealing so that I can have perfect conversions from JsValue's into my native Rust types, see here: https://github.com/boa-dev/boa/issues/1961#issuecomment-1075673692

**Comment by Razican** [comment]
> So that you can extract the values that couldn't be converted to JSON and handle them as you would prefer.

I don't see this so useful. JSON conversion can happen at a nested object level, so you wouldn't really know where is the error coming from. JSON doesn't accept `BigInt` or `undefined`, but it also doesn't accept `Symbol`, for example. So, we cannot implement a conversion to JSON for these types, and it will of course fail.

The easy conversion from `JsValue` to arbitrary Rust types (and back) would be the best option here if JSON is not the required output. But I'm closing this issue for now, since there is nothing we can do about this, we cannot change the JSON spec.
