### ISSUE TITLE
Do we need `STATIC_STRINGS`?

### ISSUE THREAD

**Issue by YXL76** [boa-dev/boa#2040]
Currently, there are some static strings defined in boa_interner.

https://github.com/boa-dev/boa/blob/3de921e600123fb4ec188d6120eaba45fe413a92/boa_interner/src/lib.rs#L370-L398

But unlike the `CONSTANTS` in `JsString` can reduce memory allocation.

https://github.com/boa-dev/boa/blob/3de921e600123fb4ec188d6120eaba45fe413a92/boa_engine/src/string.rs#L15-L161

Why not just do the hash calculation instead of iterating over `STATIC_STRINGS` each time, especially when there are more elements in STATIC_STRINGS.

https://github.com/boa-dev/boa/blob/3de921e600123fb4ec188d6120eaba45fe413a92/boa_interner/src/lib.rs#L183-L193

**Comment by raskad** [comment]
The `Interner` and `JsString` have different purposes.

The `Interner` stores strings that originate in the Javascript source code. The idea is to reduce memory usage and the cloning of strings in the AST by assigning each string a `Sym` (number). It's usage is mostly restricted to the lexer, parser and compiler.
For example for this source code:
```js
let object1 = {
    property1: "abc",
}
```
the variable name `object1` the property name `property1` and the constant string field `"abc"` are being interned.

`JsString` is the representation of Javascript string values at runtime. These cannot be interned because they can be dynamically constructed at runtime.

The `get_static` function and the iteration over `STATIC_STRINGS` only happens once per string in the source code; when the string is being interned. So it should not be that expensive.

I hope answers your question?

**Comment by YXL76** [comment]
I see what you mean, I just think `string-interner` does all the work for us, and then defining `STATIC_STRINGS` and constants in `Sym` doesn't do any good other than add complexity.

**Comment by YXL76** [comment]
I see, maybe we can add `STATIC_STRINGS` when creating Interner, then `get_static` is not needed, I don't know.

By the way, are there plans to support `Interner` across `Context`? Instead of holding a reference, each context now has an exclusive Interner.

**Comment by raskad** [comment]
> I see, maybe we can add `STATIC_STRINGS` when creating `Interner`, then `get_static` is not needed, I don't know.

That would probably be possible but we would depend on the interning order and we would have the strings once as `&'static str` in memory and once in the `Interner`.

> By the way, are there plans to support Interner across Context? Instead of holding a reference, each context now has an exclusive Interner.

It would definitely be possible. But you would have to define how long your `Interner` lives to not leak memory (or not leak too much). Do you have a specific usecase for that? It would definitely be unsafe (currently panic-safe but maybe unsafe in the future) to change the `Interner` in between any of the lexing to runtime steps for a js input script.

**Comment by YXL76** [comment]
You're right. But for static strings, `Interner` only holds the pointer.
