### ISSUE TITLE
`new.target` is not understood by the parser as an expression

### ISSUE THREAD

**Issue by vfosnar** [boa-dev/boa#2793]
**Describe the bug**
Using `new.target.<something>` throws syntax error.

**To Reproduce**
```js
class A {
    constructor() {
        console.log(new.target.name);
    }
}

const a = new A(); // should log "A"
```

**Expected behavior**
The code snippet should compile and run.

The expected behavior can be achieved using a temporary variable:
```js
class A {
    constructor() {
        let tmp = new.target;
        console.log(tmp.name);
    }
}

const a = new A(); // logs "A"
```

[MDN link for `new.target`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target)

**Comment by projectnoa** [comment]
I would like to contribute to this project. Is there any guidance you guys can provide and I can start working on it?

**Comment by Razican** [comment]
Hello @projectnoa, glad you'd like to contribute!
A good place to start is the [CONTRIBUTING.md](https://github.com/boa-dev/boa/blob/main/CONTRIBUTING.md) file. Then, I would go through the [debugging](https://github.com/boa-dev/boa/blob/main/docs/debugging.md) documentation.

The debugging documentation can prove to be very useful in this case. Using `--dump-ast` in the Boa CLI, you can see how is the code parsed. With that, you might already get an idea if the issue comes from the parser, since syntax errors are usually generated there.

Then, I would try to debug it using VSCode or any LLDB-compatible tool, and see how you get to the error. To understand the code better, you can use our [development documentation](https://boajs.dev/boa/doc/boa_engine/index.html).

Let us know, though, if things start getting too complex!

**Comment by jedel1043** [comment]
By the way, the code that parses the `new.target` node lives here:

https://github.com/boa-dev/boa/blob/ed3744817577d33fe944fd11d73843bfa0a64f8a/boa_parser/src/parser/expression/left_hand_side/member.rs#L85-L104

**Comment by projectnoa** [comment]
I managed to find the issue, as @jedel1043 pointed out, it was indeed on: [boa/boa_parser/src/parser/expression/left_hand_side/member.rs](https://github.com/boa-dev/boa/blob/ed3744817577d33fe944fd11d73843bfa0a64f8a/boa_parser/src/parser/expression/left_hand_side/member.rs#L85-L104)

The fix I provided in the pull request addresses the issue and all tests pass. However, in my attempt to create a unittest to validate this fix I was unable to figure out the implementation pattern and make a test that works. Please feel free to help me here.

Thanks!
