### ISSUE TITLE
Is it possible to pass in an async say_hello() here: context.register_global_builtin_function("say_hello", 1, say_hello);

### ISSUE THREAD

**Issue by anfen** [boa-dev/boa#2909]
I am able to pass in a **non-async** say_hello() function here:

```
let mut context = Context::default();
context.register_global_builtin_function("say_hello", 1, say_hello);
```

But is it possible with an **async** say_hello() function? If so, what would be the syntax please?

**Comment by jedel1043** [comment]
Yep! You'll need to switch to the `main` branch instead of the 1.16 version. There's an example on how to run futures (and hook a future executor like tokio) on the `futures.rs` example:

https://github.com/boa-dev/boa/blob/c2205052bc8389a5370a69fa02b475e722eb508d/boa_examples/src/bin/futures.rs 

Though, there are some caveats about creating `NativeFunction`s from async functions; see [`NativeFunction::from_async_fn`](https://boajs.dev/boa/doc/boa_engine/struct.NativeFunction.html#method.from_async_fn)

**Comment by anfen** [comment]
Excellent, thank you.
