### ISSUE TITLE
oxc as AST Parser?

### ISSUE THREAD

**Issue by mishushakov** [boa-dev/boa#3430]
Could Boa gain significant performance by adopting [OXC](https://github.com/web-infra-dev/oxc) parser?

**Comment by jedel1043** [comment]
While using an external parser could be better to improve parsing performance, the engine prioritizes compilation and execution performance first and foremost, even when having to do more work at parse time (e.g. string interning).

I imagine this approach would go against the priorities of oxc and many other ES parsers, which is why we have a custom parser that can be tailored by us to prioritize execution performance.

**Comment by mishushakov** [comment]
Thanks so much for the explanation! I will be closing the issue now 😄
