### ISSUE TITLE
`boa_engine::property::PropertyKey` has several fallible `From` impls

### ISSUE THREAD

**Issue by LikeLakers2** [boa-dev/boa#4049]
Hi there! I was looking into Boa out of curiousity.

I noticed that `boa_engine::property::PropertyKey`'s documentation lists several `From` impls that are not infallible. For example, `From<u64>` or `From<f64>`.

I understand that this may be due to the use of `Into<PropertyKey>` on `boa_engine::class::ClassBuilder`'s methods (among other things). However, `From` impls are intended to be infallible. From the documentation on `core::convert::From`:

> **Note: This trait must not fail.** The `From` trait is intended for perfect conversions. If the conversion can fail or is not perfect, use [`TryFrom`](https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html).

I would recommend changing the offending `From` impls to `TryFrom`, and any uses of `Into<PropertyKey>` to `TryInto<PropertyKey>`.

Do note that any `From` impls that are infallible can remain untouched, due to the blanket impl `impl<T, U> TryFrom<U> for T where U: Into<T>` from the Rust `core` library.

P.S. I suspect there may be other cases of this within `boa` - and if there are, I would recommend fixing those too!

**Comment by jedel1043** [comment]
Thank you for checking out Boa!

I'm pretty sure those conversions are infallible. The ECMAScript standard defines only string and symbol keys, but we internally have integer keys as an optimization.

If an `f64` or an `u64` doesn't fit within our `NonMaxU32`, it would be against the spec to reject those valid values. Instead, what we do is to get the string representation of the value so that it can still be used as a proper key.

**Comment by LikeLakers2** [comment]
Ah, you're right. It seems I misread the code - specifically, I saw the calls to `Result::ok()` and thought that they would panic if the Result was an `Err()`

My bad!
