### ISSUE TITLE
[executor] Use of undefined variable should throw an error

### ISSUE THREAD

**Issue by croraf** [boa-dev/boa#463]
**Describe the bug**
```js
console.log(d);
console.log(d());
d;
d();
```

Any of the above statements should throw an error `ReferenceError: d is not defined`

**Comment by Razican** [comment]
For anyone willing to work on this, this has two sides:
 implemented in [here][ident_exec] for identifiers execution. This will go to the Realm environment record and call [get_binding_value()][env_binding_val]. This will either return the value, or `Undefined`.

This is not 100% spec compliant. The [spec][ident_spec] says that this should call the "abstract" operation [`ResolveBinding`][resolve_binding], with no environment pre-set. Then, this should call to [`GetIdentifierReference`][get_ident_ref] (Note that Boa doesn't implement strict mode yet). We currently don't have `Reference` implemented, either, so, the current implementation does a fine job returning an `undefined`, but we lack information on the binding name. The main issue here, is that we should be calling `GetValue` on this returned reference, if I'm not mistaken.

As we can see in the formal [specification][get_value_spec] of this function, we should throw a `ReferenceError` if the value is not defined. Ideally, we should implement `Reference` and its `get_value()` function that would be 100% spec compliant.

Note that this type of error is not implemented in Boa yet, and we only have the general `Error`, the `TypeError` and the `RangeError`, as you can see [here][errors].

To implement a new one, you can base your implementation in the [`RangeError` implementation][range_error], for example, and then add a helper to the interpreter in the [exceptions list][exceptions] to easily throw one if needed.

A bit of extra information about `ReferenceError` can be found in the [spec][reference_error_spec].

About the calling of an undefined variable, is implemented [here][call]. This is calling `interpreter.call`, which is implemented [here][interp_call] with its spec [here][call_spec]. This is not spec compliant, but we can improve it greatly, and even make it spec compliant. It should first not check `func` to se if it's callable, since we recently implemented `is_callable()` on values. This should throw a `TypeError`, not panic, in the case that the value is not callable.

But we are missing here the `ReferenceError`. This is coming from [here][call_expr_spec], from the second part, that does `CallExpression: CallExpression Arguments`. Here, when we evaluate the call expression, we get the undefined `d` Reference, and should be calling `get_value()` on it, which should throw the `ReferenceError`.

I think we should first fix the `d;` case by implementing `Reference` and `get_value()`, and then, fix the `Call` implementation.

[ident_exec]: https://github.com/boa-dev/boa/blob/master/boa/src/exec/mod.rs#L428-L434
[env_binding_val]: https://github.com/boa-dev/boa/blob/master/boa/src/environment/lexical_environment.rs#L215-L220
[ident_spec]: https://tc39.es/ecma262/#sec-identifiers-runtime-semantics-evaluation
[resolve_binding]: https://tc39.es/ecma262/#sec-resolvebinding
[get_ident_ref]: https://tc39.es/ecma262/#sec-getidentifierreference
[get_value_spec]: https://tc39.es/ecma262/#sec-getvalue
[errors]: https://github.com/boa-dev/boa/tree/master/boa/src/builtins/error
[range_error]: https://github.com/boa-dev/boa/blob/master/boa/src/builtins/error/range.rs
[exceptions]: https://github.com/boa-dev/boa/blob/master/boa/src/exec/exception.rs
[reference_error_spec]: https://tc39.es/ecma262/#sec-native-error-types-used-in-this-standard-referenceerror
[call]: https://github.com/boa-dev/boa/blob/master/boa/src/exec/expression/mod.rs#L13-L55
[interp_call]: https://github.com/boa-dev/boa/blob/master/boa/src/exec/mod.rs#L127-L141
[call_spec]: https://tc39.es/ecma262/#sec-call
[call_expr_spec]: https://tc39.es/ecma262/#sec-function-calls-runtime-semantics-evaluation
