### ISSUE TITLE
[builtins - Object]  Object.defineProperties() not implemented

### ISSUE THREAD

**Issue by croraf** [boa-dev/boa#552]
Also, as per: https://github.com/boa-dev/boa/pull/543#discussion_r450857804 , after this is done, `Object.create` should be improved to handle second argument (the object properties) along with some tests.

**Comment by Razican** [comment]
Hi, this seems to be a new enhancement request, not something that is buggy. Could you please fill the template we have for this? There are no links to the spec or proper explanations on what this means.

**Comment by croraf** [comment]
Which explaination you need on "Object.defineProperties() not implemented"?

**Comment by Razican** [comment]
> It is not clear which of these should be selected in this case. Perhaps "Feature request" description should be improved.

Done in #554.

> Which explaination you need on "Object.defineProperties() not implemented"?

Do you have a link to the spec where this is explained? A code example that you would like to make work?

Also, you mention `Object.create`. What is this second parameter? Do you have a link to the spec? An example code? You mention we should add new tests. Which tests? why?

**Comment by croraf** [comment]
> Do you have a link to the spec where this is explained? A code example that you would like to make work?
> 

 It should not be my job as a end-user and reported to suggest the way how to implement it, and provide suggestions where to find the information. This should be at the reporters discretion on add this or not. The issue and request is perfectly clear as is.


> Also, you mention `Object.create`. What is this second parameter? Do you have a link to the spec? An example code? You mention we should add new tests. Which tests? why?

Although I think this is also clear, I added a link to the related closed issue.

**Comment by Razican** [comment]
> It should not be my job as a end-user and issue reported to suggest the way how to implement it, and provide suggestions where to find the information. The reporter should have a discretion to add this or not. The issue report is perfectly clear as is.

Sure, but understand that the more detail you give, the more possibilities you have for us to take this into account.

In any case, let me add some information for future developers.

This is defined in the spec [here](https://tc39.es/ecma262/#sec-object.defineproperties). This should be added to the `Object` global object in [this](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/object/mod.rs) file, similarly to the [`Object.create()`](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/object/mod.rs#L413-L441) method.

Then, this needs to be added as a property of the `Object` in the [end of the file](https://github.com/boa-dev/boa/blob/master/boa/src/builtins/object/mod.rs#L554), and we could take the opportunity to fix the `Object.create()` method above by taking into account the second parameter, instead of panicking.

Note that this `Object.defineProperties()` will require first calling on `get_type()` to assert the type of the object, but in fact, this can be a bit more efficient by doing an `if let` in the `Value`.

Then, in the spec, you call `ToObject()`, which is defined in the interpreter [here](https://github.com/boa-dev/boa/blob/ca0eaeadb286b5869fe7ae090e0fa3c47b980c13/boa/src/exec/mod.rs#L483-L568).

Then it calls `ToPropertyDescriptor()` and `DefinePropertyOrThrow()`, which I think they are not defined. And in fact, we might not be properly using property descriptor. Maybe @HalidOdat or @jasonwilliams can give a hint.

**Comment by HalidOdat** [comment]
> Then it calls `ToPropertyDescriptor()` and `DefinePropertyOrThrow()`, which I think they are not defined. And in fact, we might not be properly using property descriptor. Maybe @HalidOdat or @jasonwilliams can give a hint.

Yes. `ToPropertyDescriptor()` and  `DefinePropertyOrThrow()` are not implemented, I planed to fix/implement (the internal methods are not spec compliant) them after #553

**Comment by dvtkrlbs** [comment]
I can take a look at this

**Comment by jasonwilliams** [comment]
Now that the blockers are out the way this should be straight forward for someone to pick up

**Comment by dvtkrlbs** [comment]
i can take this issue

**Comment by dvtkrlbs** [comment]
Ok i am creating the Object.defineProperties function but i did not understand something in the spec.
`Let keys be ? props.[[OwnPropertyKeys]]().` what this means and is it defined already in the source code. I see these things are defined [here](https://tc39.es/ecma262/#table-essential-internal-methods) but i dont understand if i should define them myself.

**Comment by croraf** [comment]
@dvtkrlbs I guess that should be a method of Rust's `Object` structure that seems not to be implemented, so should be implemented within this task or before this task. (Also you should join discord channel for boa for easier discussion. Link should be on the homepage)

**Comment by jasonwilliams** [comment]
> Ok i am creating the Object.defineProperties function but i did not understand something in the spec.
> `Let keys be ? props.[[OwnPropertyKeys]]().` what this means and is it defined already in the source code. I see these things are defined [here](https://tc39.es/ecma262/#table-essential-internal-methods) but i dont understand if i should define them myself.

I imagine your "defineProperties" will be similar to this:
https://github.com/boa-dev/boa/blob/master/boa/src/builtins/object/mod.rs#L98-L105

> Let keys be ? props.[[OwnPropertyKeys]]().
This means loop through each key in the object's property list.
The `?` just means each access shouldn't result in an abrupt ending
