### ISSUE TITLE
Implement the "Comma" operator

### ISSUE THREAD

**Issue by Razican** [boa-dev/boa#569]
**ECMASCript feature**
The comma operator allows dividing expressions and running them all one after the other, returning the rightmost result. The `Comma` punctuator is already being lexed, but it fails to parse, because it has no binary operation associated [here][as_binop].

We should define a binary operation [here][binop] and then define how it should be executed [here][exec_binop].

[as_binop]: https://github.com/boa-dev/boa/blob/4beadfc9adf91f9b0fb467cc9fe57549699722e8/boa/src/syntax/ast/punctuator.rs#L133-L172
[binop]: https://github.com/boa-dev/boa/blob/master/boa/src/syntax/ast/op.rs#L680-L708
[exec_binop]: https://github.com/boa-dev/boa/blob/master/boa/src/exec/operator/mod.rs#L52-L143

The functionality is described [here][spec], in the ECMAScript specification, and extra information can be found in MDN [here][mdn].

[spec]: https://tc39.es/ecma262/#sec-comma-operator
[mdn]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator

**Example code**
The following code now panics, but should work properly once this is implemented:

```javascript
var a, b;
b = 10;
a = (b++, b);
a;
```
The expected output is `11`.

**Comment by KashParty** [comment]
Hi, I've tried to implement this and it works for the example given (the output is 11, as expected) and other similar cases. However, I found some issues with my naive solution. For example:

```js
var a, b;
b = 10;
a = (b += 1, b);
a;

// Outputs 20
```

This should be identical to the example given above, but it seems to ignore the 1, and runs `b += b` instead. So far I have only seen this behavior for assignment operators. Originally, I thought that I had done something wrong, but then I also found this example (which can even be produced in Boa Playground):

```js
// Evaluates to true
a = false && b = true;

// Evaluates to false
a = true && b = false;
```

This is similar because it also seems to "skip" the middle part and just runs `a = true` and `a = false` each time. I can't say for sure whether it's related to the issues I'm experiencing with the comma operator.

Since I'm completely new to this project, I'm not sure where to go from here, since this could either be something wrong with my implementation of the comma operator, or something bigger than that.

My guess is that `b += 1, b` is evaluated as `b += (1, b)` and that simplifies to `b += b`. Any suggestions?

**Comment by HalidOdat** [comment]
Hey @KashParty 

Hmmm. Interesting. About the second one, it is a bug, but not as we expected, the bug is that this works `anyNonAssignableExpression = 4` and it evaluates to `4`, this is wrong and should throw a `SyntaxError`. and when we do this `a = false && b = true;` or `a = true && b = false;` the operation on order is right `a = ((false && b) = true)`, this is because assignment has [low precedence](http://www-lia.deis.unibo.it/materiale/JS/developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence.html) and `&&` is evaluated first and this happens: `a = false && b = true;` => `a = (false && b) = true` => `a = ((false && b) = true)`. when we start evaluating it the bug appears we assign to `(false && b) = true` at this point it should throw a `SyntaxError`, but id doesn't and evaluate to `true` so we get `a = (true)` and this evaluates to `true`

I'm not sure about the first one though, I haven't checked your implementation.

hope this helps :)
