### ISSUE TITLE
Fully implement the spread operator

### ISSUE THREAD

**Issue by elasmojs** [boa-dev/boa#619]
Hi

console.log(sum.apply(null, numbers));

expected output: 6
got: undefined

thanks

**Comment by jasonwilliams** [comment]
@elasmojs could you add more information? 
I don't see spread syntax being used here?

**Comment by elasmojs** [comment]
@jasonwilliams it is directly from the MDN javascript docs, I have use the first demo example in the link below, hope it helps
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by Razican** [comment]
The spread operator is not implemented afaik. It just returns the element once.

**Comment by dvtkrlbs** [comment]
I can grab this issue

**Comment by dvtkrlbs** [comment]
Can i get some guidance on this. I can see that we parse a Spread object. But if i understand correctly the spec defines different behaviour on spreads depending on the context (in function calls, array inits, object inits).

**Comment by croraf** [comment]
Spread operator is implemented for the arrays, it was partially working before in a wrong implementation, so I did a fix to make a more proper implementation in https://github.com/boa-dev/boa/pull/811. @Razican Can you adjust the title so it correctly describes what is done here, because also the initial issue comment is completely unclear. The best would be to close this and open a new issue.
