### ISSUE TITLE
Error in passing string value to function of type NativeFunctionData

### ISSUE THREAD

**Issue by elasmojs** [boa-dev/boa#633]
Hi

The dev branch seems pass string values along with quotes when passing arguments to functions of type NativeFunctionData

thanks

**Comment by HalidOdat** [comment]
> The dev branch seems pass string values along with quotes when passing arguments to functions of type NativeFunctionData

Could you give an example of this?

**Comment by elasmojs** [comment]
> Could you give an example of this?

I just issued a pull request for #446 (#634) , it has the snippet in modulehandler.rs line #44
hope that helps

**Comment by HalidOdat** [comment]
This is not a bug, when you call `value.to_string()` it calls value `Display` trait which puts quotes around strings. instead use `Interperter::to_string(value)` after #625 this should be more intuitive. since to display it you have to call `Value::display()` and to turn the value to a string you call `Value::to_string(ctx)`.
