### ISSUE TITLE
Implement the ECMAScript module system

### ISSUE THREAD

**Issue by oovm** [boa-dev/boa#64]
Things like implement **require/import alias**.

**Comment by jasonwilliams** [comment]
Nope, I haven't got this far yet, feel free to let us know if you have any ideas or if you wanted try something out. 
In theory the [interpreter can run multiple times against new files](https://github.com/jasonwilliams/boa/blob/master/src/lib/lib.rs#L87)

**Comment by jasonwilliams** [comment]
Work has started on import parsing https://github.com/jasonwilliams/boa/pull/259

**Comment by creepinson** [comment]
Any updates on this? The PR was closed a while ago, and i can't find another decent, embeddable rust javascript engine like this 😕

**Comment by Razican** [comment]
> Any updates on this? The PR was closed a while ago, and i can't find another decent, embeddable rust javascript engine like this 😕 
> 
> 

I will soon add a project for this, it's definitely in the pipeline, along with generators and a async/await support.

**Comment by Razican** [comment]
I'm working on the [`Module`](https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-modules) parsing now. This will probably require some changes on how we parse, since we no longer have just "scripts", we also have "modules", which require a bit of a different parsing.

Not a big deal, though. For now I will work on the parsing, and see how we go from there. I would also like to see how to adapt our tester to be able to test modules.

On the API side, I'm thinking that it would be interesting to be able to initialize the `Context` with a module loader, and we can provide a simple "file module loader" which would load modules from a given path. This would enable users to create their own module loader, so that they can import modules from files, databases, memory or from wherever they want.
