### ISSUE TITLE
length is not updating properly on string within while loop

### ISSUE THREAD

**Issue by jasonwilliams** [boa-dev/boa#720]
**Describe the bug**
while loops do not seem to be working properly. The condition doesn't seem to re-run causing infinite loops in some places. Tested on 01b5cec04f079b7efe9fe643b310a7e9ce2a415a

**To Reproduce**
Steps to reproduce the issue, or JavaScript code that causes this failure.

This JavaScript code reproduces the issue:
```javascript
function addZeros() {
    var s = "";
    while (s.length < 4) {
      s = "0" + s;
    }
    return s;
  }

  addZeros()

```

`s` is being extended but its still looping forever

This is what is breaking test262

**Comment by abhinitrpr** [comment]
Let me do it

**Comment by jasonwilliams** [comment]
I think concatenation falls into here:
https://github.com/boa-dev/boa/blob/master/boa/src/value/operations.rs#L14

But the length isn't being updated

**Comment by HalidOdat** [comment]
> I think concatenation falls into here:
> [https://github.com/boa-dev/boa/blob/master/boa/src/value/operations.rs#L14](https://github.com/boa-dev/boa/blob/master/boa/src/value/operations.rs?rgh-link-date=2020-09-27T17%3A21%3A43Z#L14)
> 
> But the length isn't being updated

This concats the strings into a primitive string not object, the problem is when we convert a string to an object, in `Value::to_object` seen in line: `s.length` (converts s to an string object)
the problem is [here](https://github.com/boa-dev/boa/blob/master/boa/src/value/mod.rs#L708) we set the value of the string but not the `length` property

**Comment by jasonwilliams** [comment]
Sorry @abhinitrpr this was breaking our builds so i needed to fix this quickly
