### ISSUE TITLE
The `length` property of an array is enumerable

### ISSUE THREAD

**Issue by tofpie** [boa-dev/boa#971]
**Describe the bug**
The `length` property of an array is enumerable, but it should not.

**To Reproduce**
This JavaScript code reproduces the issue:
```javascript
>> [].propertyIsEnumerable("length")
true
```

**Expected behavior**
`[].propertyIsEnumerable("length")` should be `false`.

**Build environment**

- OS: Windows 10
- Version: 0.10
- Target triple: x86_64-pc-windows-msvc
- Rustc version: rustc 1.48.0 (7eac88abb 2020-11-16)

**Additional context**
None

**Comment by tofpie** [comment]
I have taken a look, but I have not found anything obvious. I would be happy to fix it, but I do not know the code so well and I would need some guidance.

**Comment by Razican** [comment]
I believe this is set up here: https://github.com/boa-dev/boa/blob/master/boa/src/builtins/array/mod.rs#L61

The issue is that we are using `Attribute::all()`, which will sett all types to `true` as per https://github.com/boa-dev/boa/blob/470dbb43818dc7658a45a011856584fe60220662/boa/src/property/attribute/mod.rs

I think it should use `Attribute::default()`.

**Comment by Razican** [comment]
Actually, not, since it should be writable as per [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/length), so we should probably select the right attribute.

**Comment by tofpie** [comment]
It seems this is another bug. This causes:
```javascript
>> Array.prototype.propertyIsEnumerable("length")
true
```
This should be false. Maybe I can add the fix in the same PR?
